### ISSUE TITLE
Execution failed for task ':app:dexDebug'

### ISSUE THREAD

**Issue by brusasu** [mrmans0n/clusterer#14]
hi, i'm trying to use your library but when i add compile 'io.nlopez.clusterer:library:1.0.5' in my build.gradle file, i got this error:

Error:Execution failed for task ':app:dexDebug'.
    > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException:       Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java'' finished       with non-zero exit value 2

In the dependencies i have only this:
    dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile 'com.google.android.gms:play-services:7.0.0'
    compile 'io.nlopez.clusterer:library:1.0.5'

   }

Have you please have a fix for that error?

Regards

**Comment by mrmans0n** [comment]
You just have to add the transitive flag to the dependency

**Comment by brusasu** [comment]
Thanks for the reply. I've done the suggestion adding "transitive = true
", but i get another error: 
Error:(27, 0) No such property: transitive for class: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated

**Comment by dommerq** [comment]
I'm using `compile 'io.nlopez.clusterer:library:1.0.5'` without transitive flag and it works :/

**Comment by brusasu** [comment]
Thanks dommerq, i found the problem. In my dependencies i use alto 'compile 'com.google.android.gms:play-services:7.0.0' that seem goes in contrast with the nlopez.clusterer library. I need to use playservices in order to use gmaps v2  in my Android app.
Really don't know what to do to fix the problem.

Anyway thanks for the reply.

**Comment by brusasu** [comment]
Ok guys i fixed it. I updated the play-services to  " compile 'com.google.android.gms:play-services:7.5.0' " and now Gradle sync without errors.

Regards
